version: '3'

services:
  nginx_srv:
    container_name: nginx-uwsgi-test
    image: emarcs/nginx-uwsgi
    ports:
      - 8081:80
    links:
      - uwsgi_srv
    volumes:
      - ./data/static/:/srv/django/static/
      - ./data/media/:/srv/django/media/
  uwsgi_srv:
     image: emarcs/django
     volumes:
      - ./data:/srv/django/app
